# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
env:
  - JULIA_PROJECT="@."
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - |
#    julia --depwarn=error -e '
#      VERSION >= v"0.7.0-DEV.3656" && using Pkg
#      if VERSION >= v"0.7.0-DEV.5183" && (isfile("Project.toml") || isfile("JuliaProject.toml"))
#          Pkg.build(); Pkg.test(coverage=true)
#      else
#          Pkg.clone(pwd()); Pkg.build("EzXML"); Pkg.test("EzXML"; coverage=true)
#      end'
after_success:
  # push coverage results to Coveralls
  # - |
  #   julia -e '
  #     VERSION >= v"0.7.0-DEV.3656" && using Pkg
  #     VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("EzXML"))
  #     Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("EzXML"))
      Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("EzXML"))
      Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
